import Head from "next/head";
import styles from "./Login.module.css";
import { useState } from "react";
import Link from "next/link";

const index = () => {
  const [credentials, setCredentials] = useState({
    email: "",
    password: "",
  });

  const handleChangeInputs = (e) => {
    let { name, value } = e.target;
    setCredentials({ ...datos, [name]: value });
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    let res = await axios.post(
      `${process.env.URL_BACK}/auth/login`,
      credentials
    );
    console.log(res);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Ecommerce - Login</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/shopping-bag.png" />
      </Head>

      <main className={styles.main}>
        <form className={styles.loginContainer} onSubmit={handleSubmit}>
          <h2 className={styles.title}>Login</h2>
          <div className={styles.inputBox}>
            <label htmlFor="email" className={styles.label}>
              Email
            </label>
            <input
              className={styles.input}
              type="text"
              id="email"
              name="email"
              placeholder="Enter your email"
              value={credentials.email}
              onChange={handleChangeInputs}
              autoComplete="off"
              required="required"
            />
          </div>
          <div className={styles.inputBox}>
            <label htmlFor="password" className={styles.label}>
              Password
            </label>
            <input
              className={styles.input}
              type="password"
              id="password"
              name="password"
              placeholder="Enter your password"
              value={credentials.password}
              onChange={handleChangeInputs}
              required="required"
            />
          </div>
          <input className={styles.btnSubmit} type="submit" value={"Sign in"} />
          <Link href={"/register"}>
            <p className={styles.helpLogin}>Do you have an account?</p>
          </Link>
        </form>
      </main>
    </div>
  );
};

export default index;
