import React from "react";
import styles from "./Register.module.css";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import axios from "axios";

const Register = () => {
  const [datos, setDatos] = useState({
    email: "",
    password: "",
  });

  const handleChangeInputs = (e) => {
    let { name, value } = e.target;
    let newDatos = { ...datos, [name]: value };
    setDatos(newDatos);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!e.target.checkValidity()) {
      console.log("no enviar");
    } else {
      console.log(datos);
      let res = await axios.post(
        `${process.env.URL_BACK}/auth/register`,
        datos
      );
      console.log(res);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Ecommerce - Register</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/shopping-bag.png" />
      </Head>

      <main className={styles.main}>
        <form className={styles.loginContainer} onSubmit={handleSubmit}>
          <h2 className={styles.title}>Register</h2>
          <div className={styles.inputBox}>
            <label className={styles.label}>Email</label>
            <input
              className={styles.input}
              type="email"
              name="email"
              placeholder="Enter your email"
              value={datos.email}
              onChange={handleChangeInputs}
              required="required"
            />
          </div>
          <div className={styles.inputBox}>
            <label className={styles.label}>Fullname</label>
            <input
              className={styles.input}
              type="text"
              name="fullname"
              placeholder="Enter your fullname"
              value={datos.fullname}
              onChange={handleChangeInputs}
              required="required"
            />
          </div>
          <div className={styles.inputBox}>
            <label className={styles.label}>Phone number</label>
            <input
              className={styles.input}
              type="text"
              name="phoneNumber"
              placeholder="Enter your phone number"
              value={datos.phoneNumber}
              onChange={handleChangeInputs}
              required="required"
            />
          </div>
          <div className={styles.inputBox}>
            <label className={styles.label}>Password</label>
            <input
              className={styles.input}
              type="password"
              name="password"
              placeholder="Enter your password"
              value={datos.password}
              onChange={handleChangeInputs}
              required="required"
            />
          </div>
          <div className={styles.inputBox}>
            <label className={styles.label}>Confirm Password</label>
            <input
              className={styles.input}
              type="password"
              name="confirmPassword"
              placeholder="Confirm password"
              value={datos.confirmPassword}
              onChange={handleChangeInputs}
              required="required"
            />
          </div>
          <input className={styles.btnSubmit} type="submit" value={"Sign in"} />
        </form>
      </main>
    </div>
  );
};

export default Register;
