import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import axios from "axios";

export default function Home() {
  const [datos, setDatos] = useState({
    email: "",
    password: "",
  });

  const handleChangeInputs = (e) => {
    let { name, value } = e.target;
    let newDatos = { ...datos, [name]: value };
    setDatos(newDatos);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    if (!e.target.checkValidity()) {
      console.log("no enviar");
    } else {
      console.log(datos);
      let res = await axios.post(`${process.env.URL_BACK}/auth/login`, datos);
      console.log(res);
    }
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <form className={styles.loginContainer} onSubmit={handleSubmit}>
          <div className={styles.inputBox}>
            <input
              className={styles.input}
              type={"text"}
              name="email"
              value={datos.email}
              onChange={handleChangeInputs}
              required="required"
            />
            <span className={styles.span}>Email</span>
          </div>
          <div className={styles.inputBox}>
            <input
              className={styles.input}
              type={"text"}
              name="password"
              value={datos.password}
              onChange={handleChangeInputs}
              required="required"
            />
            <span className={styles.span}>Password</span>
          </div>
          <input type={"submit"} value={"Ingresar"} />
        </form>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
